language: objective-c
branches:
  only:
  - master
git:
  submodules: false
before_install: 
  - git submodule update --init --recursive
podfile: ./Podfile
xcode_workspace: ./Devbeers.xcworkspace
xcode_scheme: Devbeers
script: xctool -workspace ./Devbeers.xcworkspace -sdk iphonesimulator -scheme Devbeers build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
osx_image: xcode7.2
